# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Spring Configuration
spring:
  application:
    name: api-gateway
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  cloud:
    gateway:
      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS_0_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
            allowed-methods: ${SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS_0_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
            allowed-headers: ${SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS_0_ALLOWED_HEADERS:*}
            allow-credentials: ${SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS_0_ALLOW_CREDENTIALS:true}
            max-age: 3600
      
      # Route definitions - These will be overridden by environment variables
      routes:
        # Auth Service Route
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://microservice-auth-dev:8080}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/fallback/auth
        
        # Student Service Route
        - id: student-service
          uri: ${STUDENT_SERVICE_URI:http://student-management-service-dev:8080}
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: student-service
                fallbackUri: forward:/fallback/students
        
        # Teacher Service Route
        - id: teacher-service
          uri: ${TEACHER_SERVICE_URI:http://microservice-teacher-dev:8080}
          predicates:
            - Path=/api/teachers/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: teacher-service
                fallbackUri: forward:/fallback/teachers
      
      # Default filters applied to all routes
      default-filters:
        - AddRequestHeader=X-Gateway-Source, api-gateway
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        failure-rate-threshold: ${AUTH_SERVICE_FAILURE_RATE_THRESHOLD:50}
        sliding-window-size: ${AUTH_SERVICE_SLIDING_WINDOW_SIZE:10}
        minimum-number-of-calls: ${AUTH_SERVICE_MINIMUM_NUMBER_OF_CALLS:5}
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      student-service:
        failure-rate-threshold: ${STUDENT_SERVICE_FAILURE_RATE_THRESHOLD:50}
        sliding-window-size: ${STUDENT_SERVICE_SLIDING_WINDOW_SIZE:10}
        minimum-number-of-calls: ${STUDENT_SERVICE_MINIMUM_NUMBER_OF_CALLS:5}
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      teacher-service:
        failure-rate-threshold: ${TEACHER_SERVICE_FAILURE_RATE_THRESHOLD:50}
        sliding-window-size: ${TEACHER_SERVICE_SLIDING_WINDOW_SIZE:10}
        minimum-number-of-calls: ${TEACHER_SERVICE_MINIMUM_NUMBER_OF_CALLS:5}
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,circuitbreakers
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: ${LOGGING_LEVEL_GATEWAY:INFO}
    org.springframework.web.reactive: ${LOGGING_LEVEL_WEBFLUX:INFO}
    reactor.netty: ${LOGGING_LEVEL_NETTY:INFO}
    com.distrischool: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
